config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#index'

  resources :heroes do
    collection do
      get :statistics
      get :importer
      post :import
    end
  end
  
  resources :equipments do
    collection do
      get :importer
      post :import
    end
    member do
      post :duplicate
    end
  end
end

app/models/equipment.rb
require 'csv'

class Equipment < ApplicationRecord
  enum :equipment_style, { strength: 1, agility: 2, intelligence: 3 }
  enum :equipment_type, { weapon: 1, headwear: 2, bodywear: 3, footwear: 4 }
  enum :equipment_class, { normal: 1, advanced: 2, rare: 3, epic: 4, legendary: 5, mythic: 6 }

  validates_uniqueness_of :unique_key

  before_create :set_unique_key

  HEADERS = { 
    name: 'Name', equipment_type: 'Type', equipment_style: 'Style', equipment_class: 'Class',
    equipment_class_level: 'Class level', level: 'Level', unique_key: 'Key'
  }

  def set_unique_key
    self.unique_key = SecureRandom.hex(10)
  end

  class << self
    def valid_equipment_type(equipment_type)
      return 0 unless equipment_type.to_i.in?(equipment_types.values)

      equipment_type.to_i
    end

    def valid_equipment_style(equipment_style)
      return 0 unless equipment_style.to_i.in?(equipment_styles.values)

      equipment_style.to_i
    end

    def valid_equipment_class(equipment_class)
      return 0 unless equipment_class.to_i.in?(equipment_classes.values)

      equipment_class.to_i
    end

    def valid_equipment_class_level(equipment_class_level)
      return -1 unless equipment_class_level.to_i.in?([0, 1, 2, 3])

      equipment_class_level.to_i
    end

    def to_csv
      CSV.generate(headers: true) do |csv|
        csv << HEADERS.values

        all.each do |equipment|
          csv << HEADERS.keys.map { |attr| equipment.send(attr) }
        end
      end
    end

    def import(file)
      CSV.foreach(file, headers: true) do |row|
        equipment = Equipment.find_by(unique_key: row[HEADERS[:unique_key]])
        equipment = Equipment.new if equipment.blank?

        equipment.assign_attributes(
          name: row[HEADERS[:name]],
          equipment_type: row[HEADERS[:equipment_type]],
          equipment_style: row[HEADERS[:equipment_style]],
          equipment_class: row[HEADERS[:equipment_class]],
          equipment_class_level: row[HEADERS[:equipment_class_level]],
          level: row[HEADERS[:level]],
        )

        equipment.save
      end
    end
  end
end

app/controllers/equipments_controller.rb
class EquipmentsController < ApplicationController
  def index
    update_session_filter_params
    assign_filter_instance_variable

    @equipments = Equipment.order(equipment_class: :desc)
      .order(equipment_class_level: :desc)
      .order(:equipment_style)
      .order(:equipment_type)
    @equipments = @equipments.where(equipment_type: @equipment_type) if @equipment_type.nonzero?
    @equipments = @equipments.where(equipment_style: @equipment_style) if @equipment_style.nonzero?
    @equipments = @equipments.where(equipment_class: @equipment_class) if @equipment_class.nonzero?
    @equipments = @equipments.where(equipment_class_level: @equipment_class_level) if @equipment_class_level >= 0

    respond_to do |format|
      format.html

      format.csv { send_data @equipments.to_csv, filename: "equipments_#{Time.now.to_i}.csv" }
    end
  end

  def new
    @equipment = Equipment.new
  end

  def create
    @equipment = Equipment.new(equipment_params)

    if equipment.save
      redirect_to(equipments_path)
    else
      render :new
    end
  end

  def show
    @equipment = set_equipment
  end

  def duplicate
    new_equipment = equipment.dup
    new_equipment.unique_key = nil
    new_equipment.save
    redirect_to equipments_path
  end

  def edit
    @equipment = set_equipment
  end

  def update
    equipment.assign_attributes(equipment_params)

    if equipment.save
      redirect_to(equipments_path)
    else
      render :edit
    end
  end

  def destroy
    equipment.destroy

    redirect_to equipments_path
  end

  def importer; end

  def import
    file = File.open(params[:file])
    Equipment.import(file)

    redirect_to equipments_path, success: 'Equipments imported'
  end

  private

  def update_session_filter_params
    session['equipment'] ||= {}

    update_equipment_order_by_session_filter_params
    update_equipment_type_session_filter_params
    update_equipment_style_session_filter_params
    update_equipment_class_session_filter_params
    update_equipment_class_level_session_filter_params
  end

  def update_equipment_order_by_session_filter_params
    return if params[:order_by].blank?

    session['equipment']['order_by'] = params[:order_by]
  end

  def update_equipment_type_session_filter_params
    return if params[:equipment_type].blank?

    session['equipment']['equipment_type'] =
      Equipment.valid_equipment_type(params[:equipment_type])
  end

  def update_equipment_style_session_filter_params
    return if params[:equipment_style].blank?

    session['equipment']['equipment_style'] =
      Equipment.valid_equipment_style(params[:equipment_style])
  end

  def update_equipment_class_session_filter_params
    return if params[:equipment_class].blank?

    session['equipment']['equipment_class'] =
      Equipment.valid_equipment_class(params[:equipment_class])
  end

  def update_equipment_class_level_session_filter_params
    return if params[:equipment_class_level].blank?

    session['equipment']['equipment_class_level'] =
      Equipment.valid_equipment_class_level(params[:equipment_class_level])
  end

  def assign_filter_instance_variable
    @order_by = session['equipment']['order_by'] || :equipment_class
    @equipment_type = session['equipment']['equipment_type'].to_i
    @equipment_style = session['equipment']['equipment_style'].to_i
    @equipment_class = session['equipment']['equipment_class'].to_i
    @equipment_class_level = session['equipment']['equipment_class_level'] || -1
  end

  def equipment_params
    params.require(:equipment).permit(EQUIPMENT_PARAMS)
  end

  def equipment
    @equipment ||= set_equipment
  end

  def set_equipment
    Equipment.find(params[:id])
  end
end

app/helpers/equipments_helper.rb
module EquipmentsHelper
  def equipment_class(equipment)
    str = equipment.equipment_class
    return str if equipment.equipment_class_level.zero?

    str + '*' * equipment.equipment_class_level
  end

  def equipment_type_form_options
    Equipment
      .equipment_types
      .map { |equipment_type, _index| [equipment_type.to_s.titlecase, equipment_type.to_s] }
  end

  def equipment_style_form_options
    Equipment
      .equipment_styles
      .map { |equipment_style, _index| [equipment_style.to_s.titlecase, equipment_style.to_s] }
  end

  def equipment_class_form_options
    Equipment
      .equipment_classes
      .map { |equipment_class, _index| [equipment_class.to_s.titlecase, equipment_class.to_s] }
  end

  def equipmetn_class_level_form_options
    [
      ['No Stars', 0],
      ['*', 1],
      ['**', 2],
      ['***', 3]
    ]
  end

  def equipment_style_filter_options
    Equipment
      .equipment_styles
      .map { |equipment_style, value| [equipment_style.to_s.titlecase, value, @equipment_style == value] }
      .unshift(['All Styles', 0, @equipment_style.zero?])
  end

  def equipment_type_filter_options
    Equipment
      .equipment_types
      .map { |equipment_type, value| [equipment_type.to_s.titlecase, value, @equipment_type == value] }
      .unshift(['All Types', 0, @equipment_type.zero?])
  end

  def equipment_class_filter_options
    Equipment
      .equipment_classes
      .map { |equipment_class, value| [equipment_class.to_s.titlecase, value, @equipment_class == value] }
      .unshift(['All Classes', 0, @equipment_class.zero?])
  end

  def equipment_class_level_filter_options
    [
      ['All Class Level', -1, @equipment_class_level == -1],
      ['-', 0, @equipment_class_level.zero?],
      ['*', 1, @equipment_class_level == 1],
      ['**', 2, @equipment_class_level == 2],
      ['***', 3, @equipment_class_level == 3]
    ]
  end
end

app/views/equipments/_form.html.erb
<%= form_with(model: @equipment, url: submit_path, method: submit_method(equipment)) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div>
    <%= form.label :equipment_type %>
    <%= form.select :equipment_type, equipment_type_form_options %>
  </div>

  <div>
    <%= form.label :equipment_style %>
    <%= form.select :equipment_style, equipment_style_form_options %>
  </div>

  <div>
    <%= form.label :equipment_class %>
    <%= form.select :equipment_class, equipment_class_form_options %>
  </div>

  <div>
    <%= form.label :equipment_class_level %>
    <%= form.select :equipment_class_level, equipmetn_class_level_form_options %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/equipments/edit.html.erb
<h1>Edit Equipment : <%= @equipment.name %></h1>
<%= link_to 'Back', equipments_path %>

<%= render partial: 'form', locals: { equipment: @equipment, submit_path: equipment_path(@equipment) } %>

app/views/equipments/importer.html.erb
<h1>Import Heroes</h1>
<%= link_to 'Back', heroes_path %>

<%= form_with(url: import_equipments_path, method: :post) do |form| %>
  <div>
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= link_to 'Back', equipments_path, class: 'btn btn-danger' %>
    <%= form.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/equipments/index.html.erb
<%= stylesheet_link_tag "equipments", "data-turbo-track": "reload" %>
<div class="row">
  <div class="col-lg-3">
    <%= form_with(url: equipments_path, method: :get, class: 'row', data: { controller: "search-form", action: "change->search-form#submit", turbo_frame: "search_result", turboo_action: "advance" }) do |form| %>
      <div class="row">
        <div class="col-lg-6">
          <%= render partial: 'shared/filter_options', locals: { name: :equipment_style, options: equipment_style_filter_options, form: form } %>
        </div>
        <div class="col-lg-6">
          <%= render partial: 'shared/filter_options', locals: { name: :equipment_type, options: equipment_type_filter_options, form: form } %>
        </div>
        <div class="p-lg-3"></div>
        <div class="col-lg-6">
          <%= render partial: 'shared/filter_options', locals: { name: :equipment_class, options: equipment_class_filter_options, form: form } %>
        </div>
        <div class="col-lg-6">
          <%= render partial: 'shared/filter_options', locals: { name: :equipment_class_level, options: equipment_class_level_filter_options, form: form } %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-9">
    <div class="equipment-container-header">
      <h2>Showing <%= @equipments.count %> Equipments</h2>
      <div>
        <%= link_to importer_equipments_path, data: { turbo_frame: '_top'} do %>
          <i class="bi bi-upload"></i>
        <% end %>
        <%= link_to equipments_path(format: :csv), data: { turbo_frame: '_top' } do %>
          <i class="bi bi-download"></i>
        <% end %>
        <%= link_to equipments_path, data: { turbo_frame: '_top' } do %>
            <i class="bi bi-bar-chart-fill"></i>
          <% end %>
        <%= link_to new_equipment_path do %>
          <i class="bi bi-plus-square-fill"></i>
        <% end %>
      </div>
    </div>
    <div class="equipments-container">
      <div class="equipment-header">
        <div class="data">Name</div>
        <div class="data">Type</div>
        <div class="data">Style</div>
        <div class="data">Class</div>
        <div class="data">Actions</div>
      </div>
      <% @equipments.each do |equipment| %>
        <div class="equipment-container">
          <div class="data name"><%= link_to equipment.name, equipment_path(equipment) %></div>
          <div class="data"><%= equipment.equipment_type %></div>
          <div class="data"><%= equipment.equipment_style %></div>
          <div class="data"><%= equipment_class(equipment) %></div>
          <div class="data action">
            <%= link_to edit_equipment_path(equipment) do %>
              <i class="bi bi-pencil-square"></i>
            <% end %>
            <%= link_to duplicate_equipment_path(equipment), data: { 'turbo-method' => :post } do %>
              <i class="bi bi-copy"></i>
            <% end %>
            <%= link_to equipment_path(equipment), data: { 'turbo-method' => :delete } do %>
              <i class="bi bi-trash"></i>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/equipments/new.html.erb
<h1>Add Equipment</h1>
<%= link_to 'Back', equipments_path %>

<%= render partial: 'form', locals: { equipment: @equipment, submit_path: equipments_path } %>

app/views/equipments/show.html.erb
<h1><%= @equipment.name %></h1>

<div>
  <span class="btn btn-primary"><%= @equipment.equipment_style %></span>
</div>

<div>
  <b>Class : </b>
  <%= equipment_class(@equipment) %>
</div>

<div>
  <b>Level : </b>
  <%= @equipment.level %>
</div>

<div>
  <%= link_to('Back', equipments_path) %>
  <%= link_to('Edit', edit_equipment_path(@equipment)) %>
</div>