config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#index'

  resources :heroes do
    collection do
      get :statistics
      get :importer
      post :import
    end
  end
  
  resources :equipments do
    collection do
      get :importer
      post :import
    end
    member do
      post :duplicate
    end
  end
end

app/controllers/heroes_controller.rb
# frozen_string_literal: false

class HeroesController < ApplicationController
  def index
    update_session_filter_params
    assign_filter_instance_variable

    @heroes = Hero.where(hero_class: :epic).order(@order_by.to_sym => :desc)
    @heroes = @heroes.where(hero_type: @hero_type) if @hero_type.nonzero?
    @heroes = @heroes.where(hero_style: @hero_style) if @hero_style.nonzero?
    @heroes = @heroes.where(hero_role: @hero_role) if @hero_role.nonzero?

    respond_to do |format|
      format.html

      format.csv { send_data @heroes.to_csv, filename: "epic_heroes_#{Time.now.to_i}.csv" }
    end
  end

  def new
    @hero = Hero.new
  end

  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      format.html do
        if hero.save
          redirect_to heroes_path, success: 'Hero Created'
        else
          render :edit, error: first_error(hero)
        end
      end

      format.json do
        if hero.save
          render json: hero, status: :created
        else
          render json: { message: first_error(hero) }, status: :unprocessable_entity
        end
      end
    end
  end

  def show
    @hero = set_hero
  end

  def edit
    @hero = set_hero
  end

  def update
    hero.assign_attributes(hero_params)

    respond_to do |format|
      format.html do
        if hero.save
          redirect_to heroes_path, success: 'Hero Updated'
        else
          render :edit, error: first_error(hero)
        end
      end

      format.json do
        if hero.save
          render json: hero, status: :ok
        else
          render json: { message: first_error(hero) }, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    hero.destroy

    redirect_to heroes_path, success: 'Hero Deleted'
  end

  def statistics
    @hero_type = params[:hero_type].to_i
    @heroes = Hero.where(hero_class: :rare).order(:hero_type).order(:name)
    @heroes = @heroes.where(hero_type: @hero_type) if @hero_type.nonzero?

    respond_to do |format|
      format.html

      format.csv { send_data @heroes.to_csv, filename: "rare_heroes_#{Time.now.to_i}.csv"}
    end
  end

  def importer; end

  def import
    file = File.open(params[:file])
    Hero.import(file)

    redirect_to heroes_path, success: 'Heroes imported'
  end

  private

  def update_session_filter_params
    session['hero'] ||= {}

    update_hero_order_by_session_filter_params
    update_hero_type_session_filter_params
    update_hero_style_session_filter_params
    update_hero_role_session_filter_params
  end

  def update_hero_order_by_session_filter_params
    return if params[:order_by].blank?

    session['hero']['order_by'] = params[:order_by]
  end

  def update_hero_type_session_filter_params
    return if params[:hero_type].blank?

    session['hero']['hero_type'] =
      Hero.valid_hero_type(params[:hero_type])
  end

  def update_hero_style_session_filter_params
    return if params[:hero_style].blank?

    session['hero']['hero_style'] =
      Hero.valid_hero_style(params[:hero_style])
  end

  def update_hero_role_session_filter_params
    return if params[:hero_role].blank?

    session['hero']['hero_role'] =
      Hero.valid_hero_role(params[:hero_role])
  end

  def assign_filter_instance_variable
    @order_by = session['hero']['order_by'] || :combat_power
    @hero_type = session['hero']['hero_type'].to_i
    @hero_style = session['hero']['hero_style'].to_i
    @hero_role = session['hero']['hero_role'].to_i
  end

  def hero
    @hero ||= set_hero
  end

  def set_hero
    Hero.find(params[:id])
  end

  def hero_params
    params.require(:hero).permit(HERO_PARAMS)
  end
end

app/helpers/heroes_helper.rb
module HeroesHelper
  def hero_class_form_options
    Hero
      .hero_classes
      .map { |hero_class, _index| [hero_class.to_s.titlecase, hero_class.to_s] }
  end

  def hero_type_form_options
    Hero
      .hero_types
      .map { |hero_type, _index| [hero_type.to_s.titlecase, hero_type.to_s] }
  end

  def hero_role_form_options
    Hero
      .hero_roles
      .map { |hero_role, _index| [hero_role.to_s.titlecase, hero_role.to_s] }
  end

  def hero_style_form_options
    Hero
      .hero_styles
      .map { |hero_style, _index| [hero_style.to_s.titlecase, hero_style.to_s] }
  end

  def hero_class_options
    Hero
      .hero_classes
      .map { |hero_class, value| [hero_class.to_s.titlecase, value] }
      .unshift(['All Classes', 0])
  end

  def hero_type_filter_options
    Hero
      .hero_types
      .map { |hero_type, value| [hero_type.to_s.titlecase, value, @hero_type == value] }
      .unshift(['All Types', 0, @hero_type.to_i.zero?])
  end

  def hero_role_filter_options
    Hero
      .hero_roles
      .map { |hero_role, value| [hero_role.to_s.titlecase, value, @hero_role == value] }
      .unshift(['All Roles', 0, @hero_role.to_i.zero?])
  end

  def hero_style_filter_options
    Hero
      .hero_styles
      .map { |hero_style, value| [hero_style.to_s.titlecase, value, @hero_style == value] }
      .unshift(['All Styles', 0, @hero_style.to_i.zero?])
  end

  def hero_order_filter_options
    [
      ['Combat Power', 'combat_power', @order_by == 'combat_power'],
      ['Hit Point', 'hit_point', @order_by == 'hit_point'],
      ['Defence', 'defence', @order_by == 'defence'],
      ['Attack', 'attack', @order_by == 'attack'],
      ['Speed', 'speed', @order_by == 'speed']
    ]
  end
end

app/views/heroes/_form.html.erb
<%= form_with(model: hero, url: submit_path, method: submit_method(hero)) do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :count %>
    <%= form.number_field :count %>
  </div>

  <div>
    <%= form.label :combat_power %>
    <%= form.text_field :combat_power %>
  </div>

  <div>
    <%= form.label :attack %>
    <%= form.text_field :attack %>
  </div>

  <div>
    <%= form.label :defence %>
    <%= form.text_field :defence %>
  </div>

  <div>
    <%= form.label :hit_point %>
    <%= form.text_field :hit_point %>
  </div>

  <div>
    <%= form.label :speed %>
    <%= form.text_field :speed %>
  </div>

  <div>
    <%= form.label :level %>
    <%= form.text_field :level %>
  </div>

  <div>
    <%= form.label :stars %>
    <%= form.text_field :stars %>
  </div>

  <div>
    <%= form.label :hero_class %>
    <%= form.select :hero_class, hero_class_form_options %>
  </div>

  <div>
    <%= form.label :hero_type %>
    <%= form.select :hero_type, hero_type_form_options %>
  </div>

  <div>
    <%= form.label :hero_role %>
    <%= form.select :hero_role, hero_role_form_options %>
  </div>

  <div>
    <%= form.label :hero_style %>
    <%= form.select :hero_style, hero_style_form_options %>
  </div>

  <div>
    <%= link_to 'Back', heroes_path, class: 'btn btn-danger' %>
    <%= form.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/heroes/edit.html.erb
<h1>Edit <%= @hero.name %></h1>
<%= link_to 'Back', heroes_path %>

<%= render partial: 'form', locals: { hero: @hero, submit_path: hero_path(@hero) } %>

app/views/heroes/importer.html.erb
<h1>Import Heroes</h1>
<%= link_to 'Back', heroes_path %>

<%= form_with(url: import_heroes_path, method: :post) do |form| %>
  <div>
    <%= form.label :file %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= link_to 'Back', heroes_path, class: 'btn btn-danger' %>
    <%= form.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/heroes/index.html.erb
<%= stylesheet_link_tag "heroes", "data-turbo-track": "reload" %>
<div class="row">
  <div class="col-lg-3">
    <%= form_with(url: heroes_path, method: :get, class: 'row', data: { controller: "search-form", action: "change->search-form#submit", turbo_frame: "search_result", turbo_action: "advance" }) do |form| %>
      <div class="row">
        <div class="col-lg-6">
          <%= render partial: 'shared/filter_options', locals: { name: :hero_type, options: hero_type_filter_options, form: form } %>
        </div>
        <div class="col-lg-6">
          <%= render partial: 'shared/filter_options', locals: { name: :hero_role, options: hero_role_filter_options, form: form } %>
        </div>
      </div>
      <div class="p-lg-3"></div>
      <div class="row">
        <div class="col-lg-6">
          <%= render partial: 'shared/filter_options', locals: { name: :hero_style, options: hero_style_filter_options, form: form } %>
        </div>
        <div class="col-lg-6">
          <%= render partial: 'shared/filter_options', locals: { name: :order_by, options: hero_order_filter_options, form: form } %>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-lg-9">
    <%= turbo_frame_tag "search_result" do %>
      <div class="hero-header">
        <h2>Showing <%= @heroes.count %> Heroes</h2>
        <div>
          <%= link_to importer_heroes_path, data: { turbo_frame: '_top'} do %>
            <i class="bi bi-upload"></i>
          <% end %>
          <%= link_to heroes_path(format: :csv), data: { turbo_frame: '_top' } do %>
            <i class="bi bi-download"></i>
          <% end %>
          <%= link_to statistics_heroes_path, data: { turbo_frame: '_top' } do %>
            <i class="bi bi-bar-chart-fill"></i>
          <% end %>
          <%= link_to new_hero_path, data: { turbo_frame: '_top' } do %>
            <i class="bi bi-plus-square-fill"></i>
          <% end %>
        </div>
      </div>
      <div class="heroes-container">
        <div class="hero-container-header">
          <div class="data">Name</div>
          <div class="data">Type</div>
          <div class="data">Combat Power</div>
          <div class="data">Attack</div>
          <div class="data">Defence</div>
          <div class="data">Hit Point</div>
          <div class="data">Actions</div>
        </div>
        <% @heroes.each do |hero| %>
          <div class="hero-container">
            <div class="data name"><%= link_to hero.name, hero_path(hero), data: { turbo_frame: '_top' } %></div>
            <div class="data"><%= hero.hero_type %></div>
            <div class="data"><%= hero.combat_power %></div>
            <div class="data"><%= hero.attack %></div>
            <div class="data"><%= hero.defence %></div>
            <div class="data"><%= hero.hit_point %></div>
            <div class="data action">
              <%= link_to edit_hero_path(hero), data: { turbo_frame: '_top' } do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
              <%= link_to hero_path(hero), data: { 'turbo-method' => :delete } do %>
                <i class="bi bi-trash"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/heroes/new.html.erb
<h1>Add Hero</h1>
<%= link_to 'Back', heroes_path %>

<%= render partial: 'form', locals: { hero: @hero, submit_path: heroes_path } %>

app/views/heroes/show.html.erb
<h1><%= @hero.name %></h1>

<div>
  <span class="btn btn-primary"><%= @hero.hero_role %></span>
  <span class="btn btn-primary"><%= @hero.hero_style %></span>
</div>
<div>
  <b>Combat Power : </b>
  <%= @hero.combat_power %>
</div>

<div>
  <b>Attack : </b>
  <%= @hero.attack %>
</div>

<div>
  <b>Defence : </b>
  <%= @hero.defence %>
</div>

<div>
  <b>Hit Point : </b>
  <%= @hero.hit_point %>
</div>

<div>
  <b>Speed : </b>
  <%= @hero.speed %>
</div>

<div>
  <b>Level : </b>
  <%= @hero.level %>
</div>

<div>
  <b>Stars : </b>
  <%= @hero.stars %>
</div>

<div>
  <%= link_to 'Back', heroes_path, class: 'btn btn-danger' %>
</div>

app/views/heroes/statistics.html.erb
<%= stylesheet_link_tag "heroes", "data-turbo-track": "reload" %>

<div class="row">
  <div class="col-lg-3">
    <%= form_with(url: statistics_heroes_path, method: :get, class: 'row', data: { controller: "search-form", action: "change->search-form#submit", turbo_frame: "search_result", turbo_action: "advance" }) do |form| %>
      <%= render partial: 'shared/filter_options', locals: { name: :hero_type, options: hero_type_filter_options, form: form } %>
    <% end %>
  </div>
  <div class="col-lg-9">
    <%= turbo_frame_tag "search_result" do %>
      <div class="hero-header">
        <h2>Showing <%= @heroes.count %> Heroes</h2>
        <div>
          <%= link_to importer_heroes_path, data: { turbo_frame: '_top'} do %>
            <i class="bi bi-upload"></i>
          <% end %>
          <%= link_to statistics_heroes_path(format: :csv), data: { turbo_frame: '_top' } do %>
            <i class="bi bi-download"></i>
          <% end %>
          <%= link_to heroes_path, data: { turbo_frame: '_top' } do %>
            <i class="bi bi-arrow-left-square-fill"></i>
          <% end %>
          <%= link_to new_hero_path, data: { turbo_frame: '_top' } do %>
            <i class="bi bi-plus-square-fill"></i>
          <% end %>
        </div>
      </div>
      <div class="heroes-container">
        <div class="hero-container-header">
          <div class="data">Name</div>
          <div class="data">Type</div>
          <div class="data">Count</div>
          <div class="data">Actions</div>
        </div>
        <% @heroes.each do |hero| %>
          <div class="hero-container">
            <div class="data name"><%= link_to hero.name, hero_path(hero), data: { turbo_frame: '_top' } %></div>
            <div class="data"><%= hero.hero_type %></div>
            <div class="data"><%= hero.count %></div>
            <div class="data action">
              <%= link_to edit_hero_path(hero), data: { turbo_frame: '_top' } do %>
                <i class="bi bi-pencil-square"></i>
              <% end %>
              <%= link_to hero_path(hero), data: { 'turbo-method' => :delete } do %>
                <i class="bi bi-trash"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>