config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#index'

  resources :heroes do
    collection do
      get :statistics
      get :importer
      post :import
    end
  end
  
  resources :equipments do
    collection do
      get :importer
      post :import
    end
    member do
      post :duplicate
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
  Footer
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Souls', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Heroes', heroes_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Equipments', equipments_path, class: 'nav-link' %>
        </li>
      </ul>
    </div> <!-- collapsable navbar items -->
  </div>
</nav>
<div style="margin-block: 15px">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SoulsTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "theme", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>